services:
  - type: web
    name: backend-express
    env: node
    plan: free
    region: oregon
    buildCommand: npm install
    startCommand: node backend/server.js
    autoDeploy: true
    branch: main
    rootDir: .
    envVars:
      - key: NODE_ENV
        value: production
